# Generated by Django 5.2.7 on 2025-10-28 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(blank=True, help_text='Additional message or information (optional)'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(help_text='Breed of the pet (if known)', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(help_text='Primary color of the pet', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this pet record was created'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details about the pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the pet (optional)', null=True, upload_to='pet_images/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='location',
            field=models.CharField(help_text='Location where pet was lost/found', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(help_text='The user who reported this pet', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('other', 'Other')], help_text='Type of pet', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('adoptable', 'Available for Adoption')], default='lost', help_text='Current status of the pet', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about your experience with pets', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Your birth date (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='City or area where you live', max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this request was created'),
        ),
        migrations.AlterField(
            model_name='request',
            name='pet',
            field=models.ForeignKey(help_text='Pet this request is related to', on_delete=django.db.models.deletion.CASCADE, to='main.pet'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(help_text='Phone number for contact about this request', max_length=15),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('lost', 'Lost Pet Report'), ('found', 'Found Pet Report'), ('adoption', 'Adoption Inquiry')], help_text='Type of request being made', max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(help_text='User making the request', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
