# Generated by Django 5.2.7 on 2025-11-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted')], help_text='Type of activity', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this activity occurred')),
                ('actor', models.CharField(help_text='Who performed the action (user, admin, system)', max_length=50)),
                ('details', models.TextField(blank=True, help_text='Additional details about the activity')),
                ('pet', models.ForeignKey(help_text='The pet this activity is related to', on_delete=django.db.models.deletion.CASCADE, to='main.pet')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
