# Generated by Django 5.2.7 on 2025-11-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_activitylog'),
    ]

    operations = [
    ]
