# Generated by Django 5.2.7 on 2025-11-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20251113_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was created')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this notification has been read')),
                ('notification_type', models.CharField(choices=[('lost_report', 'Lost Pet Report'), ('found_report', 'Found Pet Report')], help_text='Type of notification', max_length=20)),
                ('request', models.ForeignKey(help_text='The request this notification is related to', on_delete=django.db.models.deletion.CASCADE, to='main.request')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
