# Generated by Django 5.2.7 on 2025-11-15 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person submitting', max_length=100)),
                ('email', models.EmailField(help_text='Email address for contact', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the message', max_length=200)),
                ('message', models.TextField(help_text='The message content')),
                ('submission_type', models.CharField(choices=[('general', 'General Inquiry'), ('issue_report', 'Issue Report'), ('support', 'Support Request')], default='general', help_text='Type of submission', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='pending', help_text='Current status of the submission', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this submission was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this submission was last updated')),
                ('related_pet', models.ForeignKey(blank=True, help_text='Pet this submission is related to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.pet')),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
