# Generated by Django 5.2.7 on 2025-11-15 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact_submission',
            field=models.ForeignKey(blank=True, help_text='The contact submission this notification is related to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contactsubmission'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('lost_report', 'Lost Pet Report'), ('found_report', 'Found Pet Report'), ('contact_submission', 'Contact Submission'), ('issue_report', 'Issue Report')], help_text='Type of notification', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, help_text='The request this notification is related to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.request'),
        ),
    ]
