# Generated by Django 5.2.7 on 2025-11-21 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notification_contact_submission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Photo of the pet', upload_to='pet_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this image was uploaded')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.pet')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
